spring.application.name=Backend

spring.datasource.url=jdbc:postgresql://localhost:5432/strat_testing_app
spring.datasource.username=paulbilg
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.flyway.enabled=true